mqtt:
    hostUrl: tcp://192.168.56.104:1883
    username: admin
    password: hqxkj168++
    client-id: equipment_main
    cleanSession: true
    reconnect: true
    timeout: 100
    keepAlive: 100
    defaultTopic: client:report:1
    isOpen: true
    qos: 1
